refactor: move to modules, ox_lib, style fixes
Qbox-project/qbx_vehiclefailure pull request #6
Opened 2023-09-17 20:21 UTC by MafewTM

## Description

Adds the modules, replaces the deprecated export and functions, further use of cache.vehicle, switch commands and progress bars to lib, and then some minor style fixes

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

2023-09-17 20:29 UTC, Manason approved these changes

2023-09-18 10:18 UTC, BerkieBb approved these changes

2023-09-18 10:18 UTC, BerkieBb commented on client.lua
> +		noFixMessagePos = noFixMessagePos + 1
This change was not necessary

2023-09-18 10:18 UTC, BerkieBb commented on client.lua
> +	fixMessagePos = fixMessagePos + 1
Not necessary

2023-09-18 10:18 UTC, BerkieBb commented on fxmanifest.lua
> +lua54 'yes'
Add `use_experimental_fxv2_oal 'yes'` here to use oal, it lazy loads natives and in turn speeds up the resource (or well, lower its usage)

2023-09-18 16:02 UTC, Manason commented
Fix lint check failure

2023-09-18 16:03 UTC, Manason requested changes
Fix lint check failure

2023-09-19 12:12 UTC, Manason approved these changes

2023-09-19 12:12 UTC, Manason commented on client.lua
>  		if isPedDrivingAVehicle() then
```suggestion
		if cache.seat == -1 then
```

2023-09-19 15:59 UTC, merged